/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("dev.projectg.ecodatabase.java-conventions")
}

dependencies {
    implementation("com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:2.12.4")
}

description = "common"
